/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#fdf8ee',
          100: '#f9edcf',
          200: '#f2d89b',
          300: '#eabd5e',
          400: '#e4a333',
          500: '#d4881a',
          600: '#be6a13',
          700: '#9b4e13',
          800: '#7e3e16',
          900: '#693416',
          950: '#3c1a08',
        },
                dark: {
          DEFAULT: 'rgb(var(--color-dark-950) / <alpha-value>)',
          50: 'rgb(var(--color-dark-50) / <alpha-value>)',
          100: 'rgb(var(--color-dark-100) / <alpha-value>)',
          200: 'rgb(var(--color-dark-200) / <alpha-value>)',
          300: 'rgb(var(--color-dark-300) / <alpha-value>)',
          400: 'rgb(var(--color-dark-400) / <alpha-value>)',
          500: 'rgb(var(--color-dark-500) / <alpha-value>)',
          600: 'rgb(var(--color-dark-600) / <alpha-value>)',
          700: 'rgb(var(--color-dark-700) / <alpha-value>)',
          800: 'rgb(var(--color-dark-800) / <alpha-value>)',
          900: 'rgb(var(--color-dark-900) / <alpha-value>)',
          950: 'rgb(var(--color-dark-950) / <alpha-value>)',
        },
        white: 'rgb(var(--color-white) / <alpha-value>)',
        gold: '#d4a842',
        cream: '#f5f0e8',
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, rgb(var(--color-dark-950)) 0%, rgb(var(--color-dark-900)) 50%, rgb(var(--color-dark-800)) 100%)',
        'gold-gradient': 'linear-gradient(135deg, #d4a842 0%, #f0c866 50%, #d4a842 100%)',
        'card-gradient': 'linear-gradient(to bottom, transparent 50%, rgb(var(--color-dark-950) / 0.9) 100%)',
      },
      boxShadow: {
        'glow': '0 0 20px rgba(212,168,66,0.3)',
        'glow-lg': '0 0 40px rgba(212,168,66,0.4)',
        'card': '0 4px 24px rgba(0,0,0,0.12)',
        'card-hover': '0 12px 40px rgba(0,0,0,0.2)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'shimmer': 'shimmer 2s infinite linear',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
      },
    },
  },
  plugins: [],
}
